### ISSUE TITLE
Project description?

### ISSUE THREAD

**Issue by zblace** [OS4EQ/qwifi#2]
This absence of project description does not look good for project that claims eqailuty as focus - no?
I found 'Qwifi is a simple, accessible and cheap technology that can provide free audiovisual content to marginalized populations. Qwifi streams audio to local mobile phones using Wifi and an accessible user interface.' Would that fit well?

**Comment by c0deaddict** [comment]
Thanks for your feedback! I see that someone filled in the "About" on the landing page of the repo. Does this resolve your issue?

**Comment by marcelheyne** [comment]
Hi, sorry for the delay ;-) I added "Qwifi is a simple, accessible and cheap technology that can provide free audiovisual content to marginalized populations. Qwifi serves the content by creating a local Wifi network, without the need of any internet connection and independently from the electric grid." Hope that helps. We are lagging a bit with the documentation etc. for almost all repos. But we are working on it!
